filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'

tools:
    external_code_coverage:
        enabled: true
        timeout: 900
    php_sim:
        enabled: true
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
    php_changetracking:
        enabled: true