name: Continuous Integration

on:
  push:
    paths-ignore: ["**.md"]
  pull_request:
    paths-ignore: ["**.md"]

env:
  COMPOSER_FLAGS: --ansi --no-interaction --no-progress --prefer-dist

jobs:
  tests:
    name: CI

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
        os: [ubuntu-latest]
        include:
          - php-version: "7.4"
            os: windows-latest
          - php-version: "8.2"
            os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: Get composer cache directory
        id: composercache
        shell: bash
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Install latest dependencies
        run: composer update ${{ env.COMPOSER_FLAGS }}

      - name: Run tests
        run: vendor/bin/phpunit
